#!/bin/bash
# Mark video as skip

if [ -z "$1" ]; then
    echo "No file selected" >&2
    exit 1
fi

video-tracker mark "$1" skip
echo "Marked as skip: $1"
read -n 1 -s -r -p "Press any key to continue..."
